<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-78H043L" ignored="0" name="Regression" tests="5" failures="1" timestamp="2020-10-15T05:07:21 IST" time="46.521" errors="0">
  <testcase name="TestAddCity" time="0.11" classname="com.temp.test.TestsWeather"/>
  <testcase name="TestPrintCities" time="0.001" classname="com.temp.test.TestsWeather"/>
  <testcase name="unCheckCities" time="3.298" classname="com.temp.test.TestsWeather"/>
  <testcase name="getTemp" time="2.301" classname="com.temp.test.TestsWeather">
    <failure type="java.lang.AssertionError" message="For city Ajmer: The Actual temp is 23.559998 and expected is 34.0 expected [34.0] but found [23.559998]">
      <![CDATA[java.lang.AssertionError: For city Ajmer: The Actual temp is 23.559998 and expected is 34.0 expected [34.0] but found [23.559998]
at com.temp.test.TestsWeather.getTemp(TestsWeather.java:227)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- getTemp -->
  <testcase name="getTemp" time="2.323" classname="com.temp.test.TestsWeather"/>
</testsuite> <!-- Regression -->
